<?php

namespace Database\Seeders;

use App\Models\Cadet;
use App\Models\User;
use Illuminate\Database\Seeder;

class CadetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cadets = [
            // Intake 11 (intake_year = 2022)
            [
                'user_id' => User::where('email', 'nurul.huda11@rotunavy.com')->first()->id,
                'phone_number' => '60123456792',
                'gender' => 'Female',
                'rank' => 'Lt.M',
                'position' => 'CO',
                'intake_year' => 2022,
                'matric_no' => 'MATRIC001',
                'ic_number' => '950101-01-1234',
                'service_number' => 'NV/8700001',
                'current_cgpa' => 3.5,
                'past_cgpa' => 3.2,
                'BMI' => 22.5,
                'swimming_qualification' => 'Pass',
            ],
            [
                'user_id' => User::where('email', 'ahmad.faiz11@rotunavy.com')->first()->id,
                'phone_number' => '60123456793',
                'gender' => 'Male',
                'rank' => 'Lt.M',
                'position' => 'Thana',
                'intake_year' => 2022,
                'matric_no' => 'MATRIC002',
                'ic_number' => '950201-02-2345',
                'service_number' => 'NV/8700002',
                'current_cgpa' => 3.2,
                'past_cgpa' => 3.0,
                'BMI' => 24.1,
                'swimming_qualification' => 'Pass',
            ],
            [
                'user_id' => User::where('email', 'siti.sarah11@rotunavy.com')->first()->id,
                'phone_number' => '60123456794',
                'gender' => 'Female',
                'rank' => 'Lt.M',
                'position' => 'Zayn',
                'intake_year' => 2022,
                'matric_no' => 'MATRIC003',
                'ic_number' => '950301-03-3456',
                'service_number' => 'NV/8700003',
                'current_cgpa' => 3.8,
                'past_cgpa' => 3.5,
                'BMI' => 21.8,
                'swimming_qualification' => 'In Progress',
            ],
            [
                'user_id' => User::where('email', 'mohd.hafiz11@rotunavy.com')->first()->id,
                'phone_number' => '60123456795',
                'gender' => 'Male',
                'rank' => 'Lt.M',
                'position' => 'Normal',
                'intake_year' => 2022,
                'matric_no' => 'MATRIC004',
                'ic_number' => '950401-04-4567',
                'service_number' => 'NV/8700004',
                'current_cgpa' => 3.0,
                'past_cgpa' => 2.8,
                'BMI' => 23.7,
                'swimming_qualification' => 'Pass',
            ],
            [
                'user_id' => User::where('email', 'aisyah.zainal11@rotunavy.com')->first()->id,
                'phone_number' => '60123456796',
                'gender' => 'Female',
                'rank' => 'Lt.M',
                'position' => 'Normal',
                'intake_year' => 2022,
                'matric_no' => 'MATRIC005',
                'ic_number' => '950501-05-5678',
                'service_number' => 'NV/8700005',
                'current_cgpa' => 3.6,
                'past_cgpa' => 3.3,
                'BMI' => 20.2,
                'swimming_qualification' => 'Fail',
            ],

            // Intake 12 (intake_year = 2023)
            [
                'user_id' => User::where('email', 'faridah.omar12@rotunavy.com')->first()->id,
                'phone_number' => '60123456797',
                'gender' => 'Female',
                'rank' => 'PKK',
                'position' => 'CO',
                'intake_year' => 2023,
                'matric_no' => 'MATRIC006',
                'ic_number' => '940601-06-6789',
                'service_number' => 'NV/8700006',
                'current_cgpa' => 3.4,
                'past_cgpa' => 3.1,
                'BMI' => 22.9,
                'swimming_qualification' => 'Pass',
            ],
            [
                'user_id' => User::where('email', 'zulkifli.hassan12@rotunavy.com')->first()->id,
                'phone_number' => '60123456798',
                'gender' => 'Male',
                'rank' => 'PKK',
                'position' => 'Thana',
                'intake_year' => 2023,
                'matric_no' => 'MATRIC007',
                'ic_number' => '940701-07-7890',
                'service_number' => 'NV/8700007',
                'current_cgpa' => 3.1,
                'past_cgpa' => 2.9,
                'BMI' => 25.3,
                'swimming_qualification' => 'Pass',
            ],
            [
                'user_id' => User::where('email', 'noraini.ahmad12@rotunavy.com')->first()->id,
                'phone_number' => '60123456799',
                'gender' => 'Female',
                'rank' => 'PKK',
                'position' => 'Zayn',
                'intake_year' => 2023,
                'matric_no' => 'MATRIC008',
                'ic_number' => '940801-08-8901',
                'service_number' => 'NV/8700008',
                'current_cgpa' => 3.7,
                'past_cgpa' => 3.4,
                'BMI' => 21.5,
                'swimming_qualification' => 'In Progress',
            ],
            [
                'user_id' => User::where('email', 'ismail.yusof12@rotunavy.com')->first()->id,
                'phone_number' => '60123456800',
                'gender' => 'Male',
                'rank' => 'PKK',
                'position' => 'Normal',
                'intake_year' => 2023,
                'matric_no' => 'MATRIC009',
                'ic_number' => '940901-09-9012',
                'service_number' => 'NV/8700009',
                'current_cgpa' => 2.9,
                'past_cgpa' => 2.7,
                'BMI' => 24.8,
                'swimming_qualification' => 'Pass',
            ],
            [
                'user_id' => User::where('email', 'hafizah.salleh12@rotunavy.com')->first()->id,
                'phone_number' => '60123456801',
                'gender' => 'Female',
                'rank' => 'PKK',
                'position' => 'Normal',
                'intake_year' => 2023,
                'matric_no' => 'MATRIC010',
                'ic_number' => '941001-10-0123',
                'service_number' => 'NV/8700010',
                'current_cgpa' => 3.3,
                'past_cgpa' => 3.0,
                'BMI' => 19.8,
                'swimming_qualification' => 'Fail',
            ],

            // Intake 13 (intake_year = 2024)
            [
                'user_id' => User::where('email', 'azman.ali13@rotunavy.com')->first()->id,
                'phone_number' => '60123456802',
                'gender' => 'Male',
                'rank' => 'PK',
                'position' => 'CO',
                'intake_year' => 2024,
                'matric_no' => 'MATRIC011',
                'ic_number' => '931101-11-1234',
                'service_number' => 'NV/8700011',
                'current_cgpa' => 3.5,
                'past_cgpa' => 3.2,
                'BMI' => 23.4,
                'swimming_qualification' => 'Pass',
            ],
            [
                'user_id' => User::where('email', 'sabrina.mohd13@rotunavy.com')->first()->id,
                'phone_number' => '60123456803',
                'gender' => 'Female',
                'rank' => 'PK',
                'position' => 'Thana',
                'intake_year' => 2024,
                'matric_no' => 'MATRIC012',
                'ic_number' => '931201-12-2345',
                'service_number' => 'NV/8700012',
                'current_cgpa' => 3.9,
                'past_cgpa' => 3.6,
                'BMI' => 22.1,
                'swimming_qualification' => 'Pass',
            ],
            [
                'user_id' => User::where('email', 'faizal.ramli13@rotunavy.com')->first()->id,
                'phone_number' => '60123456804',
                'gender' => 'Male',
                'rank' => 'PK',
                'position' => 'Zayn',
                'intake_year' => 2024,
                'matric_no' => 'MATRIC013',
                'ic_number' => '931301-13-3456',
                'service_number' => 'NV/8700013',
                'current_cgpa' => 3.2,
                'past_cgpa' => 3.0,
                'BMI' => 24.5,
                'swimming_qualification' => 'In Progress',
            ],
            [
                'user_id' => User::where('email', 'nora.iskandar13@rotunavy.com')->first()->id,
                'phone_number' => '60123456805',
                'gender' => 'Female',
                'rank' => 'PK',
                'position' => 'Normal',
                'intake_year' => 2024,
                'matric_no' => 'MATRIC014',
                'ic_number' => '931401-14-4567',
                'service_number' => 'NV/8700014',
                'current_cgpa' => 3.4,
                'past_cgpa' => 3.1,
                'BMI' => 20.9,
                'swimming_qualification' => 'Pass',
            ],
            [
                'user_id' => User::where('email', 'khairul.zain13@rotunavy.com')->first()->id,
                'phone_number' => '60123456806',
                'gender' => 'Male',
                'rank' => 'PK',
                'position' => 'Normal',
                'intake_year' => 2024,
                'matric_no' => 'MATRIC015',
                'ic_number' => '931501-15-5678',
                'service_number' => 'NV/8700015',
                'current_cgpa' => 2.8,
                'past_cgpa' => 2.6,
                'BMI' => 25.7,
                'swimming_qualification' => 'Fail',
            ],
        ];

        foreach ($cadets as $cadet) {
            Cadet::create($cadet);
        }
    }
}
